export const productos = [
  {
    id: "1",
    categoria: "pecheras",
    imagen: "https://i.ibb.co/BV7SPGP/pechera-Atigrada.jpg",
    titulo: "Pechera Atigrada",
    precio: 1200,
    stock: 10,
  },
  {
    id: "2",
    categoria: "pecheras",
    imagen: "https://i.ibb.co/yVpBBdy/pechera-Batman.jpg",
    titulo: "Pechera Batman",
    precio: 1200,
    stock: 10,
  },
  {
    id: "3",
    categoria: "pecheras",
    imagen: "https://i.ibb.co/SvdJ7vv/pechera-Con-Rosas.jpg",
    titulo: "Pechera con Rosas",
    precio: 1200,
    stock: 10,
  },
  {
    id: "4",
    categoria: "pecheras",
    imagen: "https://i.ibb.co/XSBqGYL/pechera-Corazones.jpg",
    titulo: "Pechera de Corazones",
    precio: 1200,
    stock: 10,
  },
  {
    id: "5",
    categoria: "pecheras",
    imagen: "https://i.ibb.co/LSYHWPz/pechera-Militar.jpg",
    titulo: "Pechera Militar",
    precio: 1200,
    stock: 10,
  },
  {
    id: "6",
    categoria: "pecheras",
    imagen: "https://i.ibb.co/8cs9wcQ/pechera-Superman.jpg",
    titulo: "Pechera Superman",
    precio: 1200,
    stock: 10,
  },
  {
    id: "7",
    categoria: "correas",
    imagen: "https://i.ibb.co/n72Tv0q/correa-Amarilla.jpg",
    titulo: "Correa Amarilla",
    precio: 1000,
    stock: 10,
  },
  {
    id: "8",
    categoria: "correas",
    imagen: "https://i.ibb.co/k4jwwrR/correa-Rayito.jpg",
    titulo: "Correa Rayito",
    precio: 1000,
    stock: 10,
  },
  {
    id: "9",
    categoria: "correas",
    imagen: "https://i.ibb.co/gVzyKQL/correa-Roja.jpg",
    titulo: "Correa Roja",
    precio: 1000,
    stock: 10,
  },
];
